// Code generated by luthier-sync. DO NOT EDIT.
package snippets

// GeneratedSnippets returns all snippets loaded from axon module luthier.yaml manifests.
func GeneratedSnippets() []Snippet {
	return []Snippet{
		{
			Module: "axon",
			Imports: []Import{
				{Path: "log/slog"},
				{Path: "net/http"},
				{Path: "os"},
				{Path: "github.com/benaskins/axon"},
			},
			Requires: []string{
				"github.com/benaskins/axon",
			},
			Setup: "\tport := os.Getenv(\"PORT\")\n\tif port == \"\" {\n\t  port = \"8080\"\n\t}\n\n\tmux := http.NewServeMux()\n\tmux.HandleFunc(\"GET /health\", func(w http.ResponseWriter, r *http.Request) {\n\t  w.WriteHeader(http.StatusOK)\n\t})",
			Helpers: "func serve(port string, mux *http.ServeMux) {\n  slog.Info(\"serving\", \"port\", port)\n  axon.ListenAndServe(port, axon.StandardMiddleware(mux))\n}",
		},
		{
			Module: "axon-auth",
			Imports: []Import{
				{Path: "os"},
				{Path: "github.com/benaskins/axon"},
			},
			Requires: []string{
				"github.com/benaskins/axon",
			},
			Setup: "\tauthURL := os.Getenv(\"AUTH_URL\")\n\tif authURL == \"\" {\n\t  authURL = \"http://localhost:9000\"\n\t}\n\tauthClient := axon.NewAuthClientPlain(authURL)\n\tdefer authClient.Close()\n\t_ = axon.RequireAuth(authClient)",
		},
		{
			Module: "axon-eval",
			Imports: []Import{
				{Path: "github.com/benaskins/axon-eval", Alias: "eval"},
			},
			Requires: []string{
				"github.com/benaskins/axon-eval",
			},
		},
		{
			Module: "axon-fact",
			Imports: []Import{
				{Path: "context"},
				{Path: "fmt"},
				{Path: "log/slog"},
				{Path: "os"},
				{Path: "github.com/benaskins/axon"},
				{Path: "github.com/benaskins/axon-fact", Alias: "fact"},
			},
			Requires: []string{
				"github.com/benaskins/axon",
				"github.com/benaskins/axon-fact",
			},
			Setup: "\tdsn := os.Getenv(\"DATABASE_URL\")\n\tif dsn == \"\" {\n\t  fmt.Fprintln(os.Stderr, \"DATABASE_URL must be set\")\n\t  os.Exit(1)\n\t}\n\tdb := axon.MustOpenDB(dsn, \"app\")\n\tevents := fact.NewPostgresStore(db,\n\t  // TODO: register domain projectors here\n\t)\n\tif err := events.Replay(context.Background()); err != nil {\n\t  slog.Error(\"replay events\", \"error\", err)\n\t  os.Exit(1)\n\t}",
		},
		{
			Module: "axon-gate",
			Imports: []Import{
				{Path: "github.com/benaskins/axon-gate", Alias: "gate"},
			},
			Requires: []string{
				"github.com/benaskins/axon-gate",
			},
		},
		{
			Module: "axon-lens",
			Imports: []Import{
				{Path: "github.com/benaskins/axon-lens", Alias: "lens"},
			},
			Requires: []string{
				"github.com/benaskins/axon-lens",
			},
		},
		{
			Module: "axon-look",
			Imports: []Import{
				{Path: "github.com/benaskins/axon-look", Alias: "look"},
			},
			Requires: []string{
				"github.com/benaskins/axon-look",
			},
		},
		{
			Module: "axon-loop",
			Imports: []Import{
				{Path: "github.com/benaskins/axon-loop", Alias: "loop"},
			},
			Requires: []string{
				"github.com/benaskins/axon-loop",
			},
			Deps: []string{
				"axon-talk",
				"axon-tool",
			},
			Setup: "\t_ = loop.RunConfig{\n\t  Client: client,\n\t  Tools:  allTools,\n\t}",
		},
		{
			Module: "axon-memo",
			Imports: []Import{
				{Path: "github.com/benaskins/axon-memo", Alias: "memo"},
			},
			Requires: []string{
				"github.com/benaskins/axon-memo",
			},
			Deps: []string{
				"axon",
			},
			Setup: "\t_ = memo.NewConversationClient(envOrDefault(\"CHAT_SERVICE_URL\", \"http://localhost:8080\"))\n\t// TODO: wire memo extractor, retriever, and consolidator",
		},
		{
			Module: "axon-mind",
			Imports: []Import{
				{Path: "github.com/benaskins/axon-mind", Alias: "mind"},
			},
			Requires: []string{
				"github.com/benaskins/axon-mind",
			},
		},
		{
			Module: "axon-nats",
			Imports: []Import{
				{Path: "github.com/benaskins/axon-nats", Alias: "nats"},
			},
			Requires: []string{
				"github.com/benaskins/axon-nats",
			},
		},
		{
			Module: "axon-synd",
			Imports: []Import{
				{Path: "github.com/benaskins/axon-synd", Alias: "synd"},
			},
			Requires: []string{
				"github.com/benaskins/axon-synd",
			},
		},
		{
			Module: "axon-talk",
			Imports: []Import{
				{Path: "fmt"},
				{Path: "log/slog"},
				{Path: "os"},
				{Path: "strings"},
				{Path: "github.com/benaskins/axon-loop", Alias: "loop"},
				{Path: "github.com/benaskins/axon-talk/anthropic"},
			},
			Requires: []string{
				"github.com/benaskins/axon-talk",
				"github.com/benaskins/axon-loop",
			},
			Setup: "\tclient := selectLLMClient()\n\tif client == nil {\n\t  fmt.Fprintln(os.Stderr, \"no LLM provider available — set ANTHROPIC_API_KEY or CLOUDFLARE_AI_GATEWAY_TOKEN\")\n\t  os.Exit(1)\n\t}",
			Helpers: "func selectLLMClient() loop.LLMClient {\n  apiKey := os.Getenv(\"ANTHROPIC_API_KEY\")\n  accountID := os.Getenv(\"CLOUDFLARE_ACCOUNT_ID\")\n  gwToken := os.Getenv(\"CLOUDFLARE_AI_GATEWAY_TOKEN\")\n\n  if accountID != \"\" && gwToken != \"\" {\n    gateway := envOrDefault(\"CLOUDFLARE_GATEWAY\", \"axon-gate\")\n    baseURL := \"https://gateway.ai.cloudflare.com/v1/\" + strings.TrimSpace(accountID) + \"/\" + gateway + \"/anthropic\"\n    slog.Info(\"using Anthropic via Cloudflare AI Gateway\", \"gateway\", gateway)\n    return anthropic.NewClient(baseURL, apiKey, anthropic.WithGatewayToken(gwToken))\n  }\n\n  if apiKey != \"\" {\n    slog.Info(\"using Anthropic API directly\")\n    return anthropic.NewClient(\"https://api.anthropic.com\", apiKey)\n  }\n\n  return nil\n}\n\nfunc envOrDefault(key, fallback string) string {\n  if v := os.Getenv(key); v != \"\" {\n    return v\n  }\n  return fallback\n}",
		},
		{
			Module: "axon-task",
			Imports: []Import{
				{Path: "github.com/benaskins/axon-task", Alias: "task"},
			},
			Requires: []string{
				"github.com/benaskins/axon-task",
			},
			Deps: []string{
				"axon-fact",
			},
			Setup: "\ttaskStore := task.NewPostgresStore(db)\n\t_ = task.NewExecutor(\"agent\", \".\", \"sonnet\", taskStore)\n\t// TODO: register workers with executor.RegisterWorker(name, worker)",
		},
		{
			Module: "axon-tool",
			Imports: []Import{
				{Path: "github.com/benaskins/axon-tool", Alias: "tool"},
			},
			Requires: []string{
				"github.com/benaskins/axon-tool",
			},
			Setup: "\tallTools := map[string]tool.ToolDef{}",
		},
		{
			Module: "axon-wire",
			Imports: []Import{
				{Path: "github.com/benaskins/axon-wire", Alias: "wire"},
			},
			Requires: []string{
				"github.com/benaskins/axon-wire",
			},
		},
	}
}
