export PATH := "/opt/homebrew/opt/postgresql@17/bin:/opt/homebrew/lib/ruby/gems/4.0.0/bin:/opt/homebrew/opt/ruby/bin:" + env_var("PATH")

rails_dir := "rails_app"

build:
    cd {{rails_dir}} && bundle exec rake assets:precompile

install:
    @echo "Run 'just server' to start the Rails application"

test:
    cd {{rails_dir}} && bin/rails test

vet:
    cd {{rails_dir}} && bin/rubocop

server:
    cd {{rails_dir}} && bin/rails server

db-setup:
    cd {{rails_dir}} && bin/rails db:create db:migrate
